baseURL = 'https://somedudeonthispage.github.io/TUDA-InteractionVR-Blog/'
languageCode = 'en-us'
title = "Interaction in Virtual and Augmented Reality"
theme = "blackburn"

copyright = "&copy; 2022. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Blog for TU-Darmstadt course in WS22/23"
  # brand = "Blackburn"
  # googleAnalytics = "Your Google Analytics tracking ID"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS photo/video sharing
  youtube = "FreakGamingLP"

  # SNS career oriented
  xing = "Robin_Buhlmann2/cv"

  # Techie
  github = "SomeDudeOnThisPage"